apiVersion: apps/v1
kind: Deployment
metadata:
  name: omar-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omar-bank-api
  template:
    metadata:
      labels:
        app: omar-bank-api
    spec:
      containers:
        - name: omar-bank-api
          image: omar-bank:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 8080
          env:
            - name: DB_DRIVER
              value: "postgres"
            - name: DB_SOURCE
              valueFrom:
                secretKeyRef:
                  name: omar-bank-secret
                  key: db-source
            - name: SERVER_ADDRESS
              value: "0.0.0.0:8080"
            - name: TOKEN_SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: omar-bank-secret
                  key: token-symmetric-key
            - name: ACCESS_TOKEN_DURATION
              value: "15m"
---
apiVersion: v1
kind: Service
metadata:
  name: omar-bank-service
spec:
  type: NodePort
  selector:
    app: omar-bank-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080