apiVersion: v1
kind: Secret
metadata:
  name: omar-bank-secret
type: Opaque
stringData:
  db-source: "postgresql://postgres:secret@postgres-service:5432/omar_bank?sslmode=disable"
  token-symmetric-key: "12345678901234567890123456789012"